# Generated by Django 4.1.3 on 2022-11-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
