# Generated by Django 4.1.3 on 2022-11-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200, unique=True)),
                ('slug1', models.SlugField(max_length=200, unique=True)),
                ('updated_on1', models.DateTimeField(auto_now=True)),
                ('content1', models.TextField()),
                ('created_on1', models.DateTimeField(auto_now_add=True)),
                ('status1', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on1'],
            },
        ),
    ]
