# Generated by Django 4.1.3 on 2022-11-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_featured_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured_article',
        ),
    ]
