# Generated by Django 4.1.7 on 2023-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='bathroom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='bed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomsleft',
            field=models.IntegerField(),
        ),
    ]
