# Generated by Django 4.1.7 on 2023-06-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_rooms_bathroom_alter_rooms_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture1'),
        ),
    ]
