# Generated by Django 4.1.7 on 2023-06-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_rooms_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('details', models.TextField(max_length=300)),
                ('roomsleft', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='picture1')),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
