# Generated by Django 4.1.7 on 2023-06-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_image_addrooms_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email_info', models.EmailField(max_length=50)),
                ('address_info', models.CharField(max_length=50)),
                ('city_info', models.CharField(max_length=50)),
                ('zip_info', models.IntegerField(max_length=50)),
                ('state_info', models.CharField(max_length=50)),
            ],
        ),
    ]
