# Generated by Django 4.1.7 on 2023-06-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='zip_info',
            field=models.IntegerField(),
        ),
    ]
