# Generated by Django 4.1.7 on 2023-06-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_information_address_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email_info',
            field=models.CharField(max_length=100),
        ),
    ]
