# Generated by Django 4.1.7 on 2023-07-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_information_email_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrooms',
            name='slug',
        ),
    ]
